name: Eleventy build and publish
on:
  push:
    branches:
      - master

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: TartanLlama/actions-eleventy@v1.2
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.6.1
        env:
          PUBLISH_DIR: dist
          PUBLISH_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
